import enum
from sqlalchemy import Column, String, Integer, Float, Boolean, JSON, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
import uuid
from Database.connection import Base

class RiskType(str, enum.Enum):
    WATER_STRESS = "WATER_STRESS"
    PEST = "PEST"
    DISEASE = "DISEASE"
    NUTRIENT_DEFICIENCY = "NUTRIENT_DEFICIENCY"
    WEATHER = "WEATHER"
    MARKET = "MARKET"

class RiskSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RiskStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    MITIGATED = "MITIGATED"

class Risk(Base):

    __tablename__ = "risks"

    id = Column(String(50), primary_key=True, default=lambda: f"risk-{uuid.uuid4().hex[:4]}")
    farm_id = Column(String(36), ForeignKey("farms.id", ondelete="CASCADE"), nullable=True, index=True)
    field_id = Column(String(50), ForeignKey("fields.id", ondelete="CASCADE"), nullable=True, index=True)
    category = Column(String(120), default="Agronomic Risk")
    risk_type = Column(String(50), default="WATER_STRESS", index=True) # WATER_STRESS, PEST, DISEASE, NUTRIENT_DEFICIENCY, WEATHER, MARKET
    severity = Column(String(20), default="HIGH", index=True) # LOW, MEDIUM, HIGH, CRITICAL
    confidence = Column(Integer, default=85)
    evidence = Column(JSON, default=list) # indicators
    explanation = Column(String(500), default="")
    recommended_action = Column(String(255), default="Recommended intervention generated by AI")

    status = Column(String(30), default="ACTIVE", index=True) # ACTIVE | RESOLVED | MITIGATED
    plan_generated = Column(Boolean, default=False)
    plan_id = Column(String(50), nullable=True)
    icon = Column(String(50), default="Droplets")
    detected_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    resolved_at = Column(DateTime, nullable=True)

    # Relationships
    farm = relationship("Farm", back_populates="risks")
    field = relationship("Field", back_populates="risks")
    advisories = relationship("AIAdvisory", back_populates="risk", cascade="all, delete-orphan")
    action_plans = relationship("ActionPlan", back_populates="risk", cascade="all, delete-orphan")
